"""initial models: episodes, scenes, jobs

Revision ID: 79fcefa3fe61
Revises: 
Create Date: 2026-07-17 11:26:15.678953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79fcefa3fe61'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('series', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('wan_fallback', sa.Boolean(), nullable=True),
    sa.Column('script_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sources_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('seo_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('wan_prompt', sa.Text(), nullable=True),
    sa.Column('output_path', sa.Text(), nullable=True),
    sa.Column('youtube_id', sa.Text(), nullable=True),
    sa.Column('duration_secs', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('scene_number', sa.Integer(), nullable=False),
    sa.Column('scene_class', sa.String(), nullable=False),
    sa.Column('voiceover_text', sa.Text(), nullable=False),
    sa.Column('manim_spec', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('wan_prompt', sa.Text(), nullable=True),
    sa.Column('audio_path', sa.Text(), nullable=True),
    sa.Column('video_path', sa.Text(), nullable=True),
    sa.Column('synced_path', sa.Text(), nullable=True),
    sa.Column('audio_duration_secs', sa.Float(), nullable=True),
    sa.Column('video_duration_secs', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenes')
    op.drop_table('jobs')
    op.drop_table('episodes')
    # ### end Alembic commands ###
